#!/bin/bash

gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0001_of_50/scattered.interval_list scattered_1.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0002_of_50/scattered.interval_list scattered_2.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0003_of_50/scattered.interval_list scattered_3.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0004_of_50/scattered.interval_list scattered_4.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0005_of_50/scattered.interval_list scattered_5.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0006_of_50/scattered.interval_list scattered_6.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0007_of_50/scattered.interval_list scattered_7.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0008_of_50/scattered.interval_list scattered_8.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0009_of_50/scattered.interval_list scattered_9.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0010_of_50/scattered.interval_list scattered_10.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0011_of_50/scattered.interval_list scattered_11.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0012_of_50/scattered.interval_list scattered_12.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0013_of_50/scattered.interval_list scattered_13.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0014_of_50/scattered.interval_list scattered_14.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0015_of_50/scattered.interval_list scattered_15.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0016_of_50/scattered.interval_list scattered_16.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0017_of_50/scattered.interval_list scattered_17.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0018_of_50/scattered.interval_list scattered_18.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0019_of_50/scattered.interval_list scattered_19.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0020_of_50/scattered.interval_list scattered_20.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0021_of_50/scattered.interval_list scattered_21.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0022_of_50/scattered.interval_list scattered_22.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0023_of_50/scattered.interval_list scattered_23.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0024_of_50/scattered.interval_list scattered_24.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0025_of_50/scattered.interval_list scattered_25.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0026_of_50/scattered.interval_list scattered_26.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0027_of_50/scattered.interval_list scattered_27.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0028_of_50/scattered.interval_list scattered_28.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0029_of_50/scattered.interval_list scattered_29.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0030_of_50/scattered.interval_list scattered_30.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0031_of_50/scattered.interval_list scattered_31.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0032_of_50/scattered.interval_list scattered_32.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0033_of_50/scattered.interval_list scattered_33.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0034_of_50/scattered.interval_list scattered_34.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0035_of_50/scattered.interval_list scattered_35.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0036_of_50/scattered.interval_list scattered_36.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0037_of_50/scattered.interval_list scattered_37.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0038_of_50/scattered.interval_list scattered_38.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0039_of_50/scattered.interval_list scattered_39.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0040_of_50/scattered.interval_list scattered_40.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0041_of_50/scattered.interval_list scattered_41.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0042_of_50/scattered.interval_list scattered_42.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0043_of_50/scattered.interval_list scattered_43.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0044_of_50/scattered.interval_list scattered_44.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0045_of_50/scattered.interval_list scattered_45.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0046_of_50/scattered.interval_list scattered_46.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0047_of_50/scattered.interval_list scattered_47.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0048_of_50/scattered.interval_list scattered_48.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0049_of_50/scattered.interval_list scattered_49.interval_list
gsutil cp gs://genomics-public-data/resources/broad/hg38/v0/scattered_calling_intervals/temp_0050_of_50/scattered.interval_list scattered_50.interval_list

aws s3 sync . s3://gfb-genomics/broad-references/hg38/interval_list/
